### ISSUE TITLE
Some Joystick events missed by Joystick class.

### ISSUE THREAD

**Issue by PartierSP** [jsbsan/1945#2]
Rapid joystick movements/button presses can cause be missed by the joystick class.  This occurs when jsdev in Device_Read contains two events instead of just one.  To fix this there should be a While Not Eof(jsdev).

I fixed this on my fork of your project by placing the 'While' command before the 'Read' statements in the Device_Read Sub.  And placing the 'Wend' at the end of that Sub.

Sorry I messed up my fork of your project.  I can't re-fork it to submit proper Pull requests.  Hopefully what I have written here makes sense to you.

**Comment by jsbsan** [comment]
I don't have a joystick, and I can't check, can you send me your code?
Thanks

**Comment by PartierSP** [comment]
Here is the modified version of JoyStick.class:

[JoyStick.class.zip](https://github.com/jsbsan/1945/files/7918382/JoyStick.class.zip)

The only two changes should be on line 74 and 175 (the addition of the While and Wend lines).

And thank-you for sharing this code.  There was so much work put into it.  The game turned out quite well.  And the Joystick class has helped me out as I'm planning on using it to control my 3D printer.

**Comment by jsbsan** [comment]
Thanks to you, I just made a commit adding your changes.

**Comment by PartierSP** [comment]
e447628effde5962acb143c98a4ceeba5dc78f25 Looks good.  Tested just fine.
